from datetime import datetime
import pandas as pd

START_DATE = datetime(2023, 1, 1)
END_DATE = datetime(2025, 7, 1)
REBALANCE_FREQ = 'M'
ESTIMATION_WINDOW = 252

MAX_WEIGHT = 0.1
RISK_FREE_RATE = 0.05

BOOTSTRAP_PATHS = 1000
FORECAST_HORIZON = 21
ARIMA_ORDER = (2, 0, 1)
XGB_LAGS = 11

TRANSACTION_COSTS = [5, 10, 20, 50]

DATA_DIR = 'data'
PLOTS_DIR = 'plots'
MODELS_DIR = 'models'

NIFTY50_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'HINDUNILVR.NS',
    'ICICIBANK.NS', 'KOTAKBANK.NS', 'WIPRO.NS', 'LT.NS', 'HDFC.NS',
    'BAJFINANCE.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'ITC.NS', 'BHARTIARTL.NS',
    'ULTRACEMCO.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'TITAN.NS', 'TECHM.NS',
    'HCLTECH.NS', 'POWERGRID.NS', 'ADANIENT.NS', 'JSWSTEEL.NS', 'TATASTEEL.NS',
    'BAJAJFINSV.NS', 'DIVISLAB.NS', 'EICHERMOT.NS', 'TATAMOTORS.NS', 'GRASIM.NS',
    'NESTLEIND.NS', 'HEROMOTOCO.NS', 'BRITANNIA.NS', 'M&M.NS', 'INDUSINDBK.NS',
    'COALINDIA.NS', 'ONGC.NS', 'DRREDDY.NS', 'HDFCLIFE.NS', 'SBILIFE.NS',
    'ADANIPORTS.NS', 'CIPLA.NS', 'APOLLOHOSP.NS', 'TATACONSUM.NS', 'BPCL.NS',
    'SBIN.NS', 'BAJAJ-AUTO.NS', 'UPL.NS', 'GAIL.NS', 'TATAPOWER.NS'
]

XGB_PARAMS = {
    'n_estimators': 100,
    'max_depth': 5,
    'learning_rate': 0.1,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'random_state': 42
}
